### ISSUE TITLE
Role should support a user group instead of a single docker user

### ISSUE THREAD

**Issue by onitake** [swisstxt/ansible-role-docker#2]
In some cases, a single Docker user is not sufficient.
This role should support adding multiple users to the docker group, and it should *not* create users and home directories. It should also send a notification when groups are updated, so services can restart when necessary.

Example implementation:
```
- name: add users to docker group
  user:
    name: "{{ item }}"
    append: yes
    groups: docker
  with_items: "{{ docker_users }}"
  notify: docker users updated
```
